//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tromps_Restoration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hire_Order
    {
        public int orderId { get; set; }
        public int Customer_ID { get; set; }
        public int Machine_ID { get; set; }
        public System.DateTime Date_Booked_Out { get; set; }
        public System.DateTime Date_Booked_In { get; set; }
        public string Invoice_Number { get; set; }
        public decimal Cost_Per_Day { get; set; }
        public Nullable<decimal> Total_Cost { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Machine Machine { get; set; }
    }
}
