//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tromps_Restoration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public string InvoiceNo { get; set; }
        public string HirerName { get; set; }
        public string HirerAddress { get; set; }
        public string HirerTelNo { get; set; }
        public string HirerIdentityNo { get; set; }
        public string HirerCarReg { get; set; }
        public string HirerCarMakeModel { get; set; }
        public string AddressWhereUsed { get; set; }
        public string SpecialInstructions { get; set; }
        public Nullable<decimal> InitialPaymentReceived { get; set; }
        public System.DateTime StartOfHire { get; set; }
        public System.DateTime EquipmentDueBack { get; set; }
        public System.DateTime EndOfHire { get; set; }
        public string EquipmentNos { get; set; }
        public decimal EquipmentSubtotal { get; set; }
        public string Accessories { get; set; }
        public Nullable<decimal> AccessoriesSubtotal { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Delivery { get; set; }
        public Nullable<decimal> Collection { get; set; }
        public Nullable<decimal> Other { get; set; }
        public decimal GrandTotal { get; set; }
        public string HowDidYouKnowUs { get; set; }
        public System.DateTime InvoiceDate { get; set; }
    }
}
